FROM nvcr.io/nvidia/pytorch:21.05-py3

RUN pip install --no-cache-dir runx==0.0.6
RUN pip install --no-cache-dir numpy
RUN pip install --no-cache-dir sklearn
RUN pip install --no-cache-dir h5py
RUN pip install --no-cache-dir jupyter
RUN pip install --no-cache-dir scikit-image
RUN pip install --no-cache-dir pillow
RUN pip install --no-cache-dir piexif
RUN pip install --no-cache-dir cffi
RUN pip install --no-cache-dir tqdm
RUN pip install --no-cache-dir dominate
# original dockerfile canoot import cv2
RUN pip install --no-cache-dir opencv-contrib-python==4.5.5.62   
# original dockerfile canoot import cv2
RUN apt install libgl1-mesa-glx    
RUN pip install --no-cache-dir nose 
RUN pip install --no-cache-dir ninja
# tools for cityscapes dataset
RUN python -m pip install cityscapesscripts   
# code formatter
RUN pip install -U flake8
RUN pip install -U autopep8
# tools
RUN pip install wandb
RUN pip install --ignore-installed ruamel.yaml
# mmcv
RUN pip install -U openmim
RUN install mmcv

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install libgtk2.0-dev -y && rm -rf /var/lib/apt/lists/*

# Install Apex
WORKDIR /home/runner
RUN cd /home/runner && git clone https://gitee.com/hyuyao/apex.git apex && cd apex && git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0 && python setup.py install --cuda_ext --cpp_ext