FROM nvidia/cuda:11.3.0-devel-ubuntu20.04
LABEL maintainer="Daisy-GENG <rgengaa@connect.ust.hk>"
# Just in case we need it
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y --no-install-recommends git curl wget git zsh tmux vim g++
# needs to be done before we can apply the patches
RUN git config --global user.email "janeandrebecca@outlook.com"
RUN git config --global user.name "Daisy-GENG"

# install zsh
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t robbyrussell \
    -p git \
    -p ssh-agent \
    -p https://github.com/agkozak/zsh-z \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting


# ==========> INSTALL ROS noetic <=============
RUN apt update && apt install -y curl lsb-release
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt update && apt install -y ros-noetic-desktop-full
RUN apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential -y \
    && rosdep init && rosdep update
RUN echo "source /opt/ros/noetic/setup.zsh" >> ~/.zshrc
RUN echo "source /opt/ros/noetic/setup.bashrc" >> ~/.bashrc

# tools for cityscapes dataset
RUN python -m pip install cityscapesscripts   
# code formatter
RUN pip3 install -U flake8
RUN pip3 install -U autopep8
# mmcv
RUN pip3 install -U openmim
RUN install mmcv

# pytorch
RUN apt update && apt install -y python3-pip
RUN pip3 install torch==1.10.0+cu113 torchvision==0.11.0+cu113 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN apt update && apt install -y python3-setuptools
RUN mkdir -p /home/hkustgz_segnet
WORKDIR /home/hkustgz_segnet
RUN git clone https://github.com/Daisy-GENG/HKUSTGZ_SegNet.git
RUN cd ProtoSeg && pip3 install -r requirements.txt