# NOTE: KITTI360's semantic label definition is consistent with Cityscapes, 19 classes for evaluation
# 
# https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py#L60
#--------------------------------------------------------------------------------
# A list of all labels
#--------------------------------------------------------------------------------

# Please adapt the train IDs as appropriate for your approach.
# Note that you might want to ignore labels with ID 255 during training.
# Further note that the current train IDs are only a suggestion. You can use whatever you like.
# Make sure to provide your results using the original IDs and not the training IDs.
# Note that many IDs are ignored in evaluation and thus you never need to predict these!

labels = [
    #       name                     id    trainId   resultId,  category            catId     hasInstances    ignoreInEval   color   
    Label(  'void'            ,       152 ,      255 , 0,       'void'            , 0       , False        , True         , (  177, 165, 25) ),

    Label(  'drivable road'         , 114 ,      0 ,   1,       'flat'            , 0       , False        , True         , (  0, 162, 170) ),

    Label(  'sidewalk' ,              201 ,      1 ,   2,       'flat'            , 0       , False        , True         , (  162, 248, 63) ),

    Label(  'parking'           ,     241,       2 ,   3,       'flat'            , 0       , False        , True         , (  241, 241, 241) ),

    Label(  'curb'               ,    108,       3 ,   4,       'flat'            , 0       , False        , True         , (  147, 109, 6) ),

    Label(  'bike Path'           ,    138 ,     4 ,   5,       'flat'            , 0       , False        , True         , (122, 172, 9) ),

    Label(  'road marking'     ,       155 ,     5 ,   6,       'flat'            , 0       , False        , True         , ( 12, 217, 219) ),

    Label(  'low-speed road'       ,   146 ,     6 ,   7,       'flat'            , 1       , False        , False        , (7, 223, 115) ),

    Label(  'lane'             ,       159 ,     7 ,   8,       'flat'            , 1       , False        , False        , (161, 161, 149) ),

    Label(  'person'              ,    160 ,     8 ,   9,       'human'            , 1       , False        , True         , (231, 130, 130) ),

    Label(  'rider'           ,        148 ,     9 ,   10,      'human'            , 1       , False        , True         , (252, 117, 35) ),

    Label(  'car'             ,        128 ,     10 ,  11,      'vehicle'    , 2       , False        , False        , ( 92, 130, 216) ),

    Label(  'bicycle'             ,     76 ,     11 ,  12,      'vehicle'    , 2       , False        , False        , (0, 108, 114) ),

    Label(  'motorcycle'           ,    64 ,     12 ,  13,      'vehicle'    , 2       , False        , False        , (0, 68, 213) ),

    Label(  'truck'           ,         53 ,     13 ,  14,      'vehicle'    , 2       , False        , True         , (91, 0, 231) ),

    Label(  'building'           ,      136 ,    14 ,  15,      'construction'    , 2       , False        , True         , (227, 68, 255) ),

    Label(  'fence'               ,     94 ,     15 ,  16,      'construction'    , 2       , False        , True         , (168, 38, 191) ),

    Label(  'wall'                 ,    45 ,     16 ,  17,      'construction'          , 3       , False        , False        , (106, 0, 124) ),

    Label(  'vegetation'            ,   210 ,    17 ,  18,      'nature'          , 3       , False        , True         , (255, 215, 73) ),

    Label(  'terrain'        ,          180,     18 ,  19,      'nature'          , 3       , False        , False        , (209, 183, 91) ),

    Label(  'river'         ,           239 ,    19 ,  20,       'nature'          , 3       , False        , False        , (244, 255, 152 ),

    Label(  'pole'           ,          156 ,    20 ,  21,       'object'          , 4       , False        , False        , (138, 164, 165) ),

    Label(  'traffic sign'          ,   64 ,     21 ,  22,       'object'          , 4       , False        , False        , (175, 0, 106) ),

    Label(  'traffic light'         ,   84 ,     22 ,  23,       'object'             , 5       , False        , False        , ( 228, 0, 140) ),

    Label(  'road block'            ,   197 ,    23 ,  24,       'object'           , 6       , True         , False        , (234, 178, 200) ),

    Label(  'sky'                ,      196 ,    24 ,  25,       'sky'           , 6       , True         , False        , (255, 172, 172) ),
]
