// Generated by gencpp from file custom_imagemsg/CustomImage.msg
// DO NOT EDIT!


#ifndef CUSTOM_IMAGEMSG_MESSAGE_CUSTOMIMAGE_H
#define CUSTOM_IMAGEMSG_MESSAGE_CUSTOMIMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_imagemsg
{
template <class ContainerAllocator>
struct CustomImage_
{
  typedef CustomImage_<ContainerAllocator> Type;

  CustomImage_()
    : header()
    , height(0)
    , width(0)
    , encoding()
    , is_bigendian(0)
    , step(0)
    , data()  {
    }
  CustomImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , height(0)
    , width(0)
    , encoding(_alloc)
    , is_bigendian(0)
    , step(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _encoding_type;
  _encoding_type encoding;

   typedef uint8_t _is_bigendian_type;
  _is_bigendian_type is_bigendian;

   typedef uint32_t _step_type;
  _step_type step;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::custom_imagemsg::CustomImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_imagemsg::CustomImage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomImage_

typedef ::custom_imagemsg::CustomImage_<std::allocator<void> > CustomImage;

typedef boost::shared_ptr< ::custom_imagemsg::CustomImage > CustomImagePtr;
typedef boost::shared_ptr< ::custom_imagemsg::CustomImage const> CustomImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_imagemsg::CustomImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_imagemsg::CustomImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_imagemsg::CustomImage_<ContainerAllocator1> & lhs, const ::custom_imagemsg::CustomImage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.encoding == rhs.encoding &&
    lhs.is_bigendian == rhs.is_bigendian &&
    lhs.step == rhs.step &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_imagemsg::CustomImage_<ContainerAllocator1> & lhs, const ::custom_imagemsg::CustomImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_imagemsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_imagemsg::CustomImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_imagemsg::CustomImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_imagemsg::CustomImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65213790a52b547e9126a9b77c2895f1";
  }

  static const char* value(const ::custom_imagemsg::CustomImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65213790a52b547eULL;
  static const uint64_t static_value2 = 0x9126a9b77c2895f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_imagemsg/CustomImage";
  }

  static const char* value(const ::custom_imagemsg::CustomImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 height\n"
"uint32 width\n"
"string encoding\n"
"uint8 is_bigendian\n"
"uint32 step\n"
"uint16[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_imagemsg::CustomImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.encoding);
      stream.next(m.is_bigendian);
      stream.next(m.step);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_imagemsg::CustomImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_imagemsg::CustomImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "encoding: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.encoding);
    s << indent << "is_bigendian: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_bigendian);
    s << indent << "step: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.step);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_IMAGEMSG_MESSAGE_CUSTOMIMAGE_H
